Mirantis/mke-docs

- content/docs/setup/README.md
- content/docs/setup/install.sh
This PR introduces an installation script that will install the following dependencies. The docs have also been updated on how to use the script.
- mkectl
- k0sctl
- kubectl
The script detects the underlying OS and ARCH and installs the correct binaries on the system.
**Reviewers P.S.** : Currently, this script installs the default versions until specified explicitly.
- mkectl (default version: v4.0.0-alpha.0.3)
- k0sctl (default version: 0.17.8)
- kubectl (default version: v1.30.0)
When the docs go public, we can add a file that updates the latest version for mkectl.. something like k0s do. https://docs.k0sproject.io/stable.txt
```
[docker@ssharma-centos7-centos-0 ~]$ sudo ./install.sh
Download wget
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: …
```
> [BOP-643] Installation script

- .github/.linkspector.yml
- content/docs/reference/monitoring/README.md
This PR adds initial documentation for MKE4 monitoring.
The original PR stopped accepting new commits when the mke-docs repo was made public. This PR incorporates the latest suggestions from that PR, including fixing the UI links (thanks, Jim) and adding config to make linkspector ignore those links (thanks, Nick).
> [BOP-602] Initial monitoring docs

- content/docs/reference/backuprestore/README.md
Markdown table was not rendering correctly.
> fix formatting backuprestore docs

- content/docs/known-issues.md
- content/docs/reference/known-issues.md
Initial Known Issues topic content, containing content from the following ENGDOCS tickets:
ENGDOCS-2387, ENGDOCS-2390, and ENGDOCS-2394
> Creation known issues topic

- content/releases/README.md
Second PR for transforming the README.md file into something of a pro…
> Second PR for transforming the README.md file into TOC with links

- content/docs/reference/authentication/authentication.md
We are not going to support disabling a component when a user wants to use there own. This removes the comments in the docs saying they can do so.
> Remove comments to disable authentication

- content/docs/setup/getting-started/k0s-in-aws/terraform/controller.tf
The terraform scripts in the `getting-started` docs used role `controller` which is not officially supported by MKE 4 yet. Manager nodes are expected to have `controller+worker` roles.
> [no jira] Fix manager node role in fresh install docs

- content/docs/setup/getting-started/install-mke4-cli.md
kubeconfig files generated by 0.18.0 use private IP addresses of the cluster nodes making it impossible to use such kubeconfig files from remote nodes (e.g. from local machine for clusters in AWS).
Thus, we should not allow using k0sctl 0.18.0.
> [BOP-821] Update allowed k0sctl versions

- hugo.yaml
* fixes issue described in <https://github.com/Mirantis/mke-docs/issues/93>
Tested using local Hugo server, ie,
1. cd to repo root dir
2. run `hugo server`
3. navigate to <http://localhost:1313/mke-docs/>
4. navigate to [Docs](http://localhost:1313/mke-docs/docs/)
5. click "Edit this page on GitHub" ⇾ it will now correctly take you to <https://github.com/Mirantis/mke-docs/edit/main/content/docs/_index.md>
6. navigate to "Operations > Authentication > SAML" ⇾ it will now correctly take you to <https://github.com/Mirantis/mke-docs/edit/main/content/docs/operations/authentication/SAML-providers/SAML.md>
> fix: URL used for 'Edit this page on GitHub'

- content/docs/operations/telemetry.md
We should **never** tell users to modify the config resource directly.
**All changes to the config must be done via mkectl apply or UI**
`kubectl edit` of the config file may lead to errors and instabilities in the cluster and should only be done by an experienced MKE 4 developer or support team member. Users should not attempt editing the config resource by themselves, and our documentation should not advertise this way of modifying the config.
> [BOP-1236] Remove instructions on direct config resource editing

- content/docs/operations/monitoring.md
- content/docs/release-notes/known-issues.md
This PR adds cadvisor docs and a few related known issues
In MKE 3, we also provided a full list of cAdvisor metrics - https://docs.mirantis.com/mke/3.7/ops/administer-cluster/collect-cluster-metrics-prometheus/cadvisor-mke-metrics.html
We could have a similar page with all metrics in MKE 4 docs as well, but I am not sure if it is up-to-date and if MKE 4 provides the same list of metrics. @nsteph could you advise on that?
> [BOP-1277] [Docs, MKE4] cadvisor

- content/docs/concepts/cni.md
updates based on changes made for cni phase 2
> cni-2 updates

- content/docs/configuration/_index.md
Changed icons to a more fitting cogs for the Configuration section index.
> Changed icon in Configuration index to cog

- content/docs/configuration/telemetry.md
Add doc to call out that MKE 4 telemetry settings are applied to the k0s configuration as well.
> [BOP-1429] Add telemetry information about k0s

- content/docs/configuration/authentication/LDAP.md
- content/docs/configuration/authentication/OIDC.md
- content/docs/configuration/authentication/SAML.md
- content/docs/configuration/authentication/_index.md
Removes the `enabled` and `redirectURI` from the config examples
> Update authentication config examples

- content/docs/getting-started/install-MKE-CLI.md
We provide a link to download mkectl for windows, but we never tested it, and windows is not officially supported by mkectl, so this PR removes the link
> Remove download link for mkectl windows binary

- content/docs/concepts/architecture.md
Updates https://mirantis.github.io/mke-docs/docs/concepts/architecture/#networking with the correct default value of `192.168.0.0/16` for Pod CIDR
> Change default POD CIDR

- content/docs/configuration/tls-certificates.md
* fixes incomplete Linux code block on the TLS certificates page
Verified via `hugo server` and reviewing locally.
> fix: incomplete Linux variable setup

- .github/workflows/pages.yaml
The upload-artifacts GHA has deprecated all versions <3. This PR updates the version so the docs action works again
**Note**
I didn't update any of the versions in the theme folder because 
- We aren't running the theme's actions
- The theme should be updated with its actual version, not our individual modifications
> Update upload-artifacts to v4

- .github/workflows/pages.yaml
Update `actions/deploy-pages` to V4
Update `actions/upload-pages-artifact` to V3
These actions require compatibility with one another. Reference their docs for more information.
> Sync artifact upload and deploy versions

- content/docs/concepts/cni.md
Updates the networking information taking into account the move to tigera-operator and allowing a direct yaml spec.
> update cni documentation for MKE 4.1
