Mirantis/mke-docs

content/docs/setup/install.sh

upgrade mkectl to latest version v4.0.0-alpha.0.5 in the installation script

[NO JIRA][installation script] upgrade mkectl to latest version v4.0.0-alpha.0.5

---

content/docs/setup/install.sh

update mkectl to latest v4.0.0-alpha1.0

---

content/releases/README.md

While waiting for other PRs to be merged, this PR solely fixes the broken link on the release page.

Fix broken links on release page

---

.gitignore
content/docs/tutorials/k0s-in-aws/terraform/lb_targets/main.tf

https://mirantis.jira.com/browse/BOP-971

[BOP-971] Improve healthchecks in TF example

---

content/docs/getting-started/install-MKE-CLI.md
content/docs/getting-started/install.sh

Bump to alpha.2.0
Move install.sh from the .md file to its original location.  Otherwise, the scripts will fail. #67

Bump alpha.2.0, restore install.sh

---

content/docs/operations/coredns-lameduck.md

Add docs for coredns lameduck feature
https://mirantis.jira.com/browse/BOP-1018

[BOP-1018] add docs for coredns lameduck

---

.gitignore
content/docs/migrate-from-MKE-3.md

https://mirantis.jira.com/browse/BOP-775
Adds information about RBAC to the migration section

[BOP-775] RBAC migration

---

content/docs/getting-started/install-MKE-CLI.md
content/docs/getting-started/install.sh

Update references to rc.1 and k0sctl version

Update for rc.1

---

content/docs/tutorials/_index.md
content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md

#91 
Adds an example of setting up an LDAP server

Add ldap server example

---

content/docs/operations/telemetry.md

Adds the correct way to update the telemetry configuration in MKE4.

Telemetry licensing

---

content/docs/operations/kubernetes/_index.md
content/docs/operations/kubernetes/kubelet-custom-profiles.md

This PR creates some initial docs for configuring the various kube components, with special attention paid to kubelet and kubelet custom profiles.

[BOP-1195] Initial docs for kubelet configuration

---

content/docs/getting-started/system-requirements.md

* add tested/supported platforms
* [style] minor reformat
cc @byDimasik

fix: supported platforms

---

content/docs/concepts/_index.md

Added missing CNI card in the Concepts section

---

content/docs/getting-started/install-MKE-CLI.md
content/docs/getting-started/install.sh

Update the mkectl version to rc3

update mkectl version to rc3

---

content/docs/getting-started/install-MKE-CLI.md
content/docs/getting-started/install.sh

Update the install script to pull rc.5 as the later

Update install script to rc.5

---

content/docs/configuration/authentication/_index.md
content/docs/migrate-from-MKE-3.md
content/docs/tutorials/k0s-in-aws/terraform-scenario.md

Found some broken links with the help of <https://www.deadlinkchecker.com/>
This PR does the following:
- fix: broken links
- fix: linter auto-reformat
Validated locally with the help of `hugo server`.

Fix broken links, apply minor formatting changes

---

content/docs/getting-started/start-interacting-with-cluster.md

Fixes issue: #253 
- fix: kubeconfig filename to mke.kubeconf

change kubeconfig filename to mke.kubeconf

---

content/docs/configuration/telemetry.md

Resolves https://github.com/Mirantis/mke-docs/issues/273

Fix typo in telemetry docs

---

.github/workflows/pages.yaml

Set the action/upload-pages-artifact to v3

Update upload-pages-artifact to v3

---

content/docs/concepts/configuration.md
content/docs/configuration/ingress/tcp-udp-services.md
content/docs/getting-started/create-cluster.md
content/docs/getting-started/start-interacting-with-cluster.md
content/docs/getting-started/uninstall-cluster.md

Update Create a Cluster topic, and correct all mke.yaml references to mke4.yaml

---

.github/workflows/pages.yaml

Deploys the docs whenever something is pushed to main (such as merging a PR)

Deploy the docs when merging to main

---

content/docs/configuration/coredns-lameduck.md

CoreDNS Lameduck topic corrections and edits

---

content/docs/release-notes/4.1.0/known-issues.md

We just discovered the issue with the freshly released 4.1.0, and we don't know the root cause yet. Therefore, we can't provide a detailed description, but still should include the issue on the list of known issues.

[BOP-2063] Add known issue for BOP-2063

---

content/docs/configuration/_index.md

Update _index.md with dashboard link (#374)

---

content/docs/getting-started/add-and-remove-cluster-nodes.md
content/docs/getting-started/create-cluster.md
content/docs/getting-started/uninstall-cluster.md

Did a run through of fresh install docs and found some minor issues with some of the commands. Mainly the commands did not work as provided and required some extra flag or step. I've fixed those in this PR.

Fix some minor technical issues in commands
